### ISSUE TITLE
Compiler Compatibility: Microsoft Visual Studio

### ISSUE THREAD

**Issue by chorman0773** [lccc-project/lccc#5]
lccc fails to compile on msvc.

This is a compliance issue with msvc, which is filed: <https://developercommunity.visualstudio.com/t/Error-C2526-C-linkage-function-cannot-r/1409254>. It provides a tracking issue on the lccc repo itself, and a place to discuss/implement workarrounds.

**Comment by rdrpenguin04** [comment]
As LCCC is no longer written in C++, this can be closed.
